"""
newsletter/html.py — convert the Markdown newsletter to a styled HTML email.

Uses a single-file HTML template with inline CSS so it renders correctly
in email clients (Gmail, Outlook, Apple Mail) without external stylesheets.
Also works as a standalone web page.

No external templating library (no Jinja2) — f-strings are readable enough
for a one-page document and eliminates another dependency.
"""

from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from scheduler.logging_setup import get_logger

logger = get_logger(__name__)

# Minimal inline-CSS email-safe styles
_CSS = """
  body { font-family: -apple-system, 'Segoe UI', Arial, sans-serif;
         background: #f5f5f5; margin: 0; padding: 20px; color: #1a1a1a; }
  .container { max-width: 680px; margin: 0 auto; background: #ffffff;
               border-radius: 8px; overflow: hidden;
               box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
  .header { background: linear-gradient(135deg, #0f172a 0%, #1e3a5f 100%);
            color: #ffffff; padding: 32px 36px; }
  .header h1 { margin: 0 0 6px 0; font-size: 22px; font-weight: 700; }
  .header .meta { color: #94a3b8; font-size: 13px; }
  .body { padding: 28px 36px; }
  .section { margin-bottom: 32px; }
  .section-title { font-size: 18px; font-weight: 700; color: #0f172a;
                   border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;
                   margin-bottom: 16px; }
  .story { margin-bottom: 20px; padding: 16px; background: #f8fafc;
           border-left: 3px solid #3b82f6; border-radius: 0 6px 6px 0; }
  .story h3 { margin: 0 0 6px 0; font-size: 15px; }
  .story h3 a { color: #1d4ed8; text-decoration: none; }
  .story h3 a:hover { text-decoration: underline; }
  .story .meta { font-size: 12px; color: #64748b; margin-bottom: 8px; }
  .story p { margin: 6px 0; font-size: 14px; line-height: 1.6; color: #374151; }
  .story .why { background: #eff6ff; border-left: 3px solid #93c5fd;
                padding: 8px 12px; border-radius: 0 4px 4px 0;
                font-size: 13px; color: #1e40af; margin-top: 8px; }
  .github-repo { margin-bottom: 14px; padding: 12px 16px;
                 background: #f0fdf4; border-left: 3px solid #22c55e;
                 border-radius: 0 6px 6px 0; }
  .github-repo h3 { margin: 0 0 4px 0; font-size: 14px; }
  .github-repo h3 a { color: #15803d; text-decoration: none; }
  .github-repo .stats { font-size: 12px; color: #166534; }
  .github-repo p { margin: 4px 0; font-size: 13px; color: #374151; }
  .takeaway { background: #fefce8; border-left: 3px solid #eab308;
              padding: 10px 14px; border-radius: 0 6px 6px 0;
              font-size: 14px; color: #713f12; margin-bottom: 10px;
              line-height: 1.6; }
  .footer { background: #f8fafc; padding: 20px 36px; text-align: center;
            font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 24px 0; }
"""


def build_html(
    markdown_content: str,
    grouped: dict[str, list[dict]],
    week_label: str,
    output_dir: str | Path = "output",
) -> str:
    """
    Generate an HTML newsletter from grouped article data.

    We use the structured `grouped` data directly rather than parsing the
    Markdown back to HTML — more reliable and gives us full control over
    the HTML structure and CSS classes.

    Returns the full HTML string and writes it to output/.
    """
    now = datetime.now(timezone.utc)
    body_html = _build_body_html(grouped, week_label)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI Weekly Intelligence Report — {week_label}</title>
  <style>{_CSS}</style>
</head>
<body>
  <div class="container">

    <div class="header">
      <h1>🤖 AI Weekly Intelligence Report</h1>
      <div class="meta">{week_label} · Generated {now.strftime("%B %d, %Y")}</div>
    </div>

    <div class="body">
      {body_html}
    </div>

    <div class="footer">
      Generated by AI Intelligence Agent · <a href="https://github.com/yourname/ai-news-agent">GitHub</a>
    </div>

  </div>
</body>
</html>"""

    # Write to disk
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    filename = f"newsletter_{_week_filename(week_label)}.html"
    filepath = output_path / filename
    filepath.write_text(html, encoding="utf-8")
    logger.info("HTML newsletter written to %s", filepath)

    return html


def _build_body_html(grouped: dict, week_label: str) -> str:
    sections: list[str] = []

    top = grouped.get("top_stories", [])
    if top:
        stories_html = "\n".join(_story_html(a) for a in top)
        sections.append(_section("🔥 Top Stories", stories_html))

    research = grouped.get("research", [])
    if research:
        stories_html = "\n".join(_story_html(a) for a in research)
        sections.append(_section("📄 Research Worth Reading", stories_html))

    tools = grouped.get("tools", [])
    if tools:
        stories_html = "\n".join(_story_html(a) for a in tools)
        sections.append(_section("🛠️ New Tools & Libraries", stories_html))

    github = grouped.get("github", [])
    if github:
        repos_html = "\n".join(_github_repo_html(r) for r in github)
        sections.append(_section("📈 Trending on GitHub", repos_html))

    takeaways_html = _build_takeaways_html(grouped)
    sections.append(_section("🎯 Career Takeaways", takeaways_html))

    total = sum(len(v) for v in grouped.values())
    est_minutes = max(5, total)
    sections.append(f'<p style="color:#64748b;font-size:13px;text-align:center;">'
                    f'_Estimated reading time: {est_minutes} minutes_</p>')

    return "\n<hr>\n".join(sections)


def _section(title: str, content: str) -> str:
    return (
        f'<div class="section">'
        f'<div class="section-title">{title}</div>'
        f'{content}'
        f'</div>'
    )


def _story_html(article: dict) -> str:
    title = _esc(article.get("title", "Untitled"))
    url = _esc(article.get("url", "#"))
    source = _esc(article.get("source", ""))
    importance = article.get("importance", 0)
    summary = _esc(article.get("summary") or article.get("content", "")[:300])
    why = _esc(article.get("why_it_matters", ""))

    why_html = f'<div class="why">💡 {why}</div>' if why else ""

    return f"""<div class="story">
  <h3><a href="{url}">{title}</a></h3>
  <div class="meta">{source} · Score: {importance:.0f}/100</div>
  <p>{summary}</p>
  {why_html}
</div>"""


def _github_repo_html(repo: dict) -> str:
    title = _esc(repo.get("title", ""))
    url = _esc(repo.get("url", "#"))
    description = _esc(repo.get("content") or repo.get("summary", ""))
    extra = repo.get("extra") or {}
    stars_today = extra.get("stars_today", 0)
    total_stars = extra.get("total_stars", 0)
    language = extra.get("language", "")

    stats_parts = []
    if language:
        stats_parts.append(f"<strong>{_esc(language)}</strong>")
    if total_stars:
        stats_parts.append(f"⭐ {total_stars:,}")
    if stars_today:
        stats_parts.append(f"↑ {stars_today:,} this week")
    stats_html = " · ".join(stats_parts)

    return f"""<div class="github-repo">
  <h3><a href="{url}">{title}</a></h3>
  <div class="stats">{stats_html}</div>
  <p>{description}</p>
</div>"""


def _build_takeaways_html(grouped: dict) -> str:
    # Reuse the same logic as markdown.py takeaways
    from newsletter.markdown import _build_career_takeaways
    raw = _build_career_takeaways(grouped)
    # Strip leading "> " from blockquote markers
    cleaned = [re.sub(r"^>\s*", "", line) for line in raw]
    return "\n".join(
        f'<div class="takeaway">💼 {_esc(line)}</div>'
        for line in cleaned if line.strip()
    )


def _esc(text: str) -> str:
    """HTML-escape a string."""
    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&#x27;")
    )


def _week_filename(week_label: str) -> str:
    m = re.search(r"Week\s+(\d+)\s*[-–]\s*(\d{4})", week_label)
    if m:
        return f"{m.group(2)}-W{int(m.group(1)):02d}"
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")
